### ISSUE TITLE
Spk10_imposter and Spk251_train 's link seems to have failed 

### ISSUE THREAD

**Issue by zhangshenyu7105** [SEC4SR/SEC4SR#2]
I'm so sorry to disturb you again,I used a proxy to download these,and encountered a 403 error after trying for two days,Others can be downloaded successfully

**Comment by SEC4SR** [comment]
Hi, maybe you can use `wget` command to manually download these datasets. It supports automatically reconnecting and transmission resuming and will save lots of your time. :smile: We have tried and found the links work fine.

**Comment by zhangshenyu7105** [comment]
OK。I would like to ask another question , is your paper on arxiv？

**Comment by SEC4SR** [comment]
No. Our paper is still under review for a conference. Due to anonymous problem, we did not upload it on arxiv.

**Comment by zhangshenyu7105** [comment]
I do hope that your paper will be accepted

> No. Our paper is still under review for a conference. Due to anonymous problem, we did not upload it on arxiv.

**Comment by SEC4SR** [comment]
> I do hope that your paper will be accepted
> 
> > No. Our paper is still under review for a conference. Due to anonymous problem, we did not upload it on arxiv.

Thanks.

**Comment by imogenqi** [comment]
Dear author, wget also can not download the dataset Spk10_imposter. What can I do for this dataset?
Thanks!

**Comment by SEC4SR** [comment]
Hi, @imogenqi and @zhangshenyu7105, thanks for your feedback. We just found that there are some permission issue with the link. We have fixed the issue.

**Comment by SEC4SR** [comment]
Please try again.

**Comment by imogenqi** [comment]
> Please try again.

Thanks for your reply ^~^
