### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'defense_flag'

### ISSUE THREAD

**Issue by muzihuole** [SEC4SR/SEC4SR#4]
Hello！Thanks for your code first.
When i run the code
 `python natural_train.py -num_epoches 30 -batch_size 128 -model_ckpt ./model_file/natural-audionet -log ./model_file/natural-audionet-log` , there is an error like this:
`Traceback (most recent call last):
  File "natural_train.py", line 196, in <module>
    main(parser_args())
  File "natural_train.py", line 73, in main
    defense, defense_name = parser_defense(args.defense, args.defense_param, args.defense_flag, args.defense_order)
AttributeError: 'Namespace' object has no attribute 'defense_flag'`
I modified the code to make it run as follows:
` File "natural_train.py", line 73
     # defense, defense_name = parser_defense(args.defense, args.defense_param, args.defense_flag, args.defense_order)
     model = defended_model(base_model=base_model)`
I want to tell you this issue.

**Comment by SEC4SR** [comment]
Hi, thanks for pointing out this issue.

I have fixed the problem by adding missing parser argument in `natural_train.py`. Pull the latest update please.

**Comment by muzihuole** [comment]
Thanks for your work. I will close this issue.
