### ISSUE TITLE
How to generate adversarial examples to attack the speaker verification system？

### ISSUE THREAD

**Issue by muzihuole** [SEC4SR/SEC4SR#5]
Hello! I try to generate adversarial examples to attack the speaker verification system. When I run the code as follow :
`python attackMain.py -threshold 13.78 -root ./data -name Spk10_imposter -des ./adver-audio/sv/xv-pgd -task SV -targeted xv_plda -model_file ./model_file/speaker_model_xv_plda PGD -epsilon 0.002 -max_iter 5 -loss Margin`
There is an error like this :
```
Running white box attack for SV task, directly using the true threshold 13.78
./adver-audio/sv/xv-pgd
0 1000
********** 0 **********
Traceback (most recent call last):
  File "attackMain.py", line 320, in <module>
    main(parse_args())
  File "attackMain.py", line 311, in main
    adver, success = attacker.attack(origin, true)
  File "C:\Lis\SEC4SR\attack\PGD.py", line 67, in attack
    adver_x_batch, success_batch = self.attack_batch(x_batch, y_batch, lower_batch, upper_batch, '{}-{}'.format(init, batch_id))
  File "C:\Lis\SEC4SR\attack\FGSM.py", line 49, in attack_batch
    scores, loss, grad, decisions = self.EOT_wrapper(x_batch, y_batch, EOT_num_batches, real_EOT_batch_size, use_grad)
  File "C:\Users\Administrator\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Lis\SEC4SR\adaptive_attack\EOT.py", line 33, in forward
    loss_EOT = self.loss(scores_EOT, y_batch_repeat)
  File "C:\Users\Administrator\.conda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Lis\SEC4SR\attack\utils.py", line 51, in forward
    assert len(enroll_index) + len(imposter_index) == label.shape[0], 'SV task should not have labels out of 0 and -1'
AssertionError: SV task should not have labels out of 0 and -1
```
 Hope to get your help. Thank you.

**Comment by muzihuole** [comment]
> Dear author, When I use the pretrained natural_audio model to generate adversarial examples, I run the code as that ` python attackMain.py -task CSI -root ./data -name Spk251_test -des ./adver-audio/audionet-fakebob audionet_csine -extractor ./model_file/natural-audionet FAKEBOB -epsilon 0.002`. However, I find an error as follow: Traceback (most recent call last): File "attackMain.py", line 320, in main(parse_args()) File "attackMain.py", line 164, in main base_model = audionet_csine(args.extractor, label_encoder=args.label_encoder, device=device) File "C:\Lis\SEC4SR\model\audionet_csine.py", line 33, in **init** num_class = model_state_dict['fc.bias'].shape[0] KeyError: 'fc.bias' Hope to get your help! Thank you.

**Comment by SEC4SR** [comment]
Since SV task only have exactly one speaker, you should use a single speaker model:
```
-model_file ./model_file/xv_plda/speaker_model_xv_plda_{SPK_ID}
```
SPK_ID is the unique id of the enrolled speaker. If you are using our datasets, then it can be chosen from `1998, 6432, 6841, 8188, 8254, 3528, 4323, 700, 7902, and 8131`.

**Comment by muzihuole** [comment]
Thanks for your reply. I will close this issue.
