### ISSUE TITLE
Why is the EER value displayed differently when the threshold is set again?

### ISSUE THREAD

**Issue by meisanhai** [SEC4SR/SEC4SR#7]
I ran 'set_threshold.py' several times for the SV task, each time displaying a different EER.  Is that a problem?  Thank you very much.

**Comment by SEC4SR** [comment]
Hi, how much is the difference? If it is tiny, it is not a problem to worry about since there is a little randomness in the MFCC extraction for `iv_plda` and `xv_plda` model.

**Comment by SEC4SR** [comment]
In the Line 180 of `torchaudio.compliance.kaldi`, you can see:
```
if dither != 0.0:
        x = torch.max(epsilon, torch.rand(strided_input.shape, device=device, dtype=dtype))
        rand_gauss = torch.sqrt(-2 * x.log()) * torch.cos(2 * math.pi * x)
        strided_input = strided_input + rand_gauss * dither
```
This is where the randomness comes from.

**Comment by meisanhai** [comment]
哦哦，结果确实相差的不多，感谢您的回复。
